---
abstract: "Generate Perl for dialogs created in wxFormBuilder\r"
author:
  - "Adam Kennedy <adamk@cpan.org>\r"
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::LongString: 0.10
  Test::More: 0.47
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Padre::Plugin::FormBuilder
name: Padre-Plugin-FormBuilder
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Class::Inspector: 1.22
  FBP::Perl: 0.75
  Padre: 0.93
  Params::Util: 0.33
  Scalar::Util: 1.19
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
